In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

In [2]:
data =  pd.read_csv("Travel.csv")
data.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

# Data Cleaning

In [3]:
data['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [4]:
data['Gender'] = data['Gender'].replace('Fe Male','Female')
data['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [5]:
data['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [6]:
data['MaritalStatus'] = data['MaritalStatus'].replace('Single','Unmarried')
data['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [7]:
data.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [8]:
features_ns = [features for features in data.columns if data[features].isnull().sum() >=1]

for feature in features_ns:
    print(feature , np.round(data[feature].isnull().mean()*100,5),"% missing values")

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [9]:
data.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [10]:
data.Age.fillna(data.Age.median(),inplace=True)

data.TypeofContact.fillna(data.TypeofContact.mode()[0],inplace=True)

data.DurationOfPitch.fillna(data.DurationOfPitch.median(),inplace=True)

data.NumberOfFollowups.fillna(data.NumberOfFollowups.median(),inplace=True)

data.PreferredPropertyStar.fillna(data.PreferredPropertyStar.mode()[0],inplace=True)

data.NumberOfTrips.fillna(data.NumberOfTrips.median(),inplace=True)

data.NumberOfChildrenVisiting.fillna(data.NumberOfChildrenVisiting.mode()[0],inplace=True)

data.MonthlyIncome.fillna(data.MonthlyIncome.median(),inplace=True)

In [11]:
data.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [12]:
data = data.drop("CustomerID",axis=1)
data

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Unmarried,3.0,1,3,1,2.0,Executive,21212.0
4885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Unmarried,3.0,0,5,0,2.0,Executive,20289.0
4887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

# Feature Engineering

In [13]:
data["TotalVisiting"] = data["NumberOfPersonVisiting"] + data["NumberOfChildrenVisiting"]

data.drop(["NumberOfChildrenVisiting","NumberOfPersonVisiting"], axis=1,inplace=True)
data.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

# Train Test Split

In [14]:
from sklearn.model_selection import train_test_split

X = data.drop("ProdTaken",axis=1)
y = data["ProdTaken"]

In [15]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

X_train.shape, X_test.shape

((3910, 17), (978, 17))

In [17]:
cat_features = X.select_dtypes(include="object").columns
num_features = X.select_dtypes(exclude="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_tranformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numeric_tranformer,num_features)
    ]
)

In [18]:
X_train = preprocessor.fit_transform(X_train)

X_test = preprocessor.transform(X_test)

In [19]:
X_train

array([[ 1.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.38224537, -0.77415132],
       [ 1.        ,  0.        ,  1.        , ...,  0.78296635,
        -0.4597992 ,  0.64361526],
       [ 1.        ,  1.        ,  0.        , ...,  0.78296635,
        -0.24519557, -0.06526803],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.36057591,  0.64361526],
       [ 1.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.25279888,  0.64361526],
       [ 0.        ,  0.        ,  1.        , ..., -1.2771941 ,
        -1.08251091, -1.48303461]], shape=(3910, 26))

# Training

In [22]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

models = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoostClassifier": AdaBoostClassifier(),
    "GradientBoostingClassifier": GradientBoostingClassifier(),
    "XgBoost": XGBClassifier()
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_test_pred = model.predict(X_test)

    print(list(models.keys())[i],"Test: ")
    print(classification_report(y_test,y_test_pred))

Decision Tree Test:
              precision    recall  f1-score   support

           0       0.94      0.95      0.95       787
           1       0.79      0.77      0.78       191

    accuracy                           0.92       978
   macro avg       0.87      0.86      0.87       978
weighted avg       0.92      0.92      0.92       978

Random Forest Test:
              precision    recall  f1-score   support

           0       0.92      0.99      0.96       787
           1       0.97      0.65      0.78       191

    accuracy                           0.93       978
   macro avg       0.94      0.82      0.87       978
weighted avg       0.93      0.93      0.92       978

AdaBoostClassifier Test:
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.75      0.24      0.36       191

    accuracy                           0.84       978
   macro avg       0.80      0.61      0.63       978
weighted avg       0.82      0.84      0.80       978

GradientBoostingClassifier Test:
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       787
           1       0.77      0.39      0.52       191

    accuracy                           0.86       978
   macro avg       0.82      0.68      0.72       978
weighted avg       0.85      0.86      0.84       978

XgBoost Test:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       787
           1       0.95      0.71      0.81       191

    accuracy                           0.94       978
   macro avg       0.94      0.85      0.89       978
weighted avg       0.94      0.94      0.93       978

# Hyperparameter Training

In [ ]:
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

ada_params = {
    "n_estimators":[50,60,70,80,90],
    "algorithm":["SAMME","SAMME.R"],

}
gradient_params={"loss": ['log_loss','deviance','exponential'],
             "criterion": ['friedman_mse','squared_error','mse'],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500],
              "max_depth": [5, 8, 15, None, 10]
                }

randomcv_models = [
                   ("RF", RandomForestClassifier(), rf_params),
                   ("AB",AdaBoostClassifier(),ada_params),
                   ("GB",GradientBoostingClassifier(),gradient_params)
                   
                ]

from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 10 candidates, totalling 30 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for RF -------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}
---------------- Best Params for AB -------------------
{'n_estimators': 80, 'algorithm': 'SAMME'}
---------------- Best Params for GB -------------------
{'n_estimators': 200, 'min_samples_split': 8, 'max_depth': 15, 'loss': 'log_loss', 'criterion': 'squared_error'}

In [23]:
models = {
    "Random Forest": RandomForestClassifier(n_estimators= 500, min_samples_split= 2, max_features= 8, max_depth=None),
    "AdaBoost": AdaBoostClassifier(n_estimators=80,algorithm='SAMME'),
    "GradientBoostingClassifier": GradientBoostingClassifier(n_estimators=200,min_samples_split=8,max_depth=15,loss="log_loss",criterion="squared_error"),
    "XGBRFClassifier": XGBClassifier(n_estimator=200, max_depth=12,learning_rate=0.1,colsample_bytre=1)
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_test_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)

    # print("Train:")
    # print(classification_report(y_train,y_train_pred))
    
    print(list(models.keys())[i],":")
    print(classification_report(y_test,y_test_pred))

Random Forest :
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       787
           1       0.96      0.71      0.82       191

    accuracy                           0.94       978
   macro avg       0.95      0.85      0.89       978
weighted avg       0.94      0.94      0.93       978

AdaBoost :
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.78      0.23      0.35       191

    accuracy                           0.84       978
   macro avg       0.81      0.60      0.63       978
weighted avg       0.83      0.84      0.80       978

GradientBoostingClassifier :
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       787
           1       0.96      0.82      0.88       191

    accuracy                           0.96       978
   macro avg       0.96      0.90      0.93       978
weighted avg       0.96      0.96      0.96       978

XGBRFClassifier :
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       787
           1       0.95      0.76      0.85       191

    accuracy                           0.95       978
   macro avg       0.95      0.88      0.91       978
weighted avg       0.95      0.95      0.94       978